# Generated by Django 2.0.7 on 2020-01-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(default='not entered', max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('door_no', models.CharField(default='not provided', max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
    ]
