# Generated by Django 2.0.7 on 2020-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_ui', '0002_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='voter_id',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='women',
            name='voter_id',
            field=models.CharField(default='not provided', max_length=200),
        ),
    ]
